-- local status, neotest = pcall(require, "neotest")
-- if not status then
-- 	print("Neotest failed")
-- end

-- -- see :h neotest.Config to modify defaults
-- neotest.setup({
-- 	adapters = {
-- 		require("neotest-python")({
-- 			dap = { justMyCode = false },
-- 			runner = "unittest",
-- 		}),
-- 		require("neotest-go")({
-- 			dap = { justMyCode = false },
-- 		}),
-- 	},
-- 	-- to get the output function to work
-- 	require("neotest-plenary"),
-- 	-- ignoring vim-test to be run on these files
-- 	-- since they are configured above.
-- 	require("neotest-vim-test")({
-- 		ignore_file_types = { "python" },
-- 	}),
-- })
