notARepository: quit
os:
  edit: "nvim"
  editPreset: "nvim"
  editAtLine: "{{editor}} {{filename}}"
gui:
  showBottomLine: false
  border: rounded
  nerdFontsVersion: "3"
  showIcons: true
  showFileTree: true
