return {
  -- {
  --   "leoluz/nvim-dap-go",
  --   lazy = true,
  --   dependencies = { "mfussenegger/nvim-dap" },
  --   ft = { "go" },
  --
  --   -- stylua: ignore
  --   keys = {
  --     -- { "<leader>dT", function() require("dap").terminate() end, desc = "Terminate" },
  --     { "<leader>dT", function() require('dap-go').debug_test() end, desc = "Debug Test" },
  --     { "<leader>dL", function() require('dap-go').debug_last() end, desc = "Debug Last" },
  --   },
  --   opts = function()
  --     local dap = require("dap")
  --
  --     dap.adapters.delve = {
  --       type = "server",
  --       port = "${port}",
  --       executable = {
  --         command = "dlv",
  --         args = { "dap", "-l", "127.0.0.1:${port}" },
  --       },
  --     }
  --
  --     -- https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv_dap.md
  --     dap.configurations.go = {
  --       {
  --         type = "delve",
  --         name = "Debug",
  --         request = "launch",
  --         program = "${file}",
  --       },
  --       {
  --         type = "delve",
  --         name = "Debug test", -- configuration for debugging test files
  --         request = "launch",
  --         mode = "test",
  --         program = "${file}",
  --       },
  --       -- works with go.mod packages and sub packages
  --       {
  --         type = "delve",
  --         name = "Debug test (go.mod)",
  --         request = "launch",
  --         mode = "test",
  --         program = "./${relativeFileDirname}",
  --       },
  --     }
  --   end,
  -- },
}
