return {
  -- {
  --   "epwalsh/obsidian.nvim",
  --   cmd = {
  --     "ObsidianToday",
  --     "ObsidianYesterday",
  --     "ObsidianNew",
  --     "ObsidianSearch",
  --     "ObsidianLink",
  --     "ObsidianLinkNew",
  --     "ObsidianBacklinks",
  --   },
  --   opts = {
  --     dir = "~/Documents/GitHub/work/brainshare/users/mattiassjodin/",
  --     daily_notes = {
  --       folder = "dailies",
  --     },
  --     notes_subdir = "notes",
  --     completion = {
  --       nvim_cmp = true,
  --     },
  --     highlight = {
  --       enable = true,
  --       additional_vim_regex_highlighting = { "markdown" },
  --     },
  --     note_id_func = function(title)
  --       -- Create note IDs in a Zettelkasten format with a timestamp and a suffix.
  --       local suffix = ""
  --       if title ~= nil then
  --         -- If title is given, transform it into valid file name.
  --         suffix = title:gsub(" ", "-"):gsub("[^A-Za-z0-9-]", ""):lower()
  --       else
  --         -- If title is nil, just add 4 random uppercase letters to the suffix.
  --         for _ = 1, 4 do
  --           suffix = suffix .. string.char(math.random(65, 90))
  --         end
  --       end
  --       return tostring(os.time()) .. "-" .. suffix
  --     end,
  --   },
  --   -- keys = {
  --   --   { "ND", ":ObsidianToday<CR>", desc = "Obsidian today", silent = false, mode = "n" },
  --   --   { "NP", ":ObsidianYesterday<CR>", desc = "Obsidian yesterday", silent = false, mode = "n" },
  --   --   { "NN", ":ObsidianNew<CR>", desc = "Obsidian new", silent = false, mode = "n" },
  --   --   { "NF", ":ObsidianSearch<CR>", desc = "Obsidian search", silent = false, mode = "n" },
  --   --   { "NL", ":ObsidianLink<CR>", desc = "Obsidian link", silent = false, mode = "v" },
  --   --   { "<leader>NL", ":ObsidianLinkNew<CR>", desc = "Obsidian link new", silent = false, mode = "v" },
  --   --   { "NB", ":ObsidianBacklinks<CR>", desc = "Obsidian backlinks", silent = false, mode = "v" },
  --   -- },
  -- },
}
