return {
  -- {
  --   "telescope.nvim",
  --   enabled = true,
  --   dependencies = {
  --     "nvim-telescope/telescope-fzf-native.nvim",
  --     build = "make",
  --     config = function()
  --       require("telescope").setup({
  --         defaults = {
  --           sorting_strategy = "ascending",
  --           layout_config = {
  --             prompt_position = "top",
  --           },
  --         },
  --       })
  --
  --       require("telescope").load_extension("fzf")
  --     end,
  --   },
  --   cmd = { "Telescope" },
  --   keys = {
  --     { "pw", "<cmd>Telescope live_grep<CR>", desc = "Live grep", silent = true, mode = "n" },
  --     { "pb", "<cmd>Telescope buffers<CR>", desc = "Buffers", silent = true, mode = "n" },
  --     { "vh", "<cmd>Telescope help_tags<CR>", desc = "Help tags", silent = true, mode = "n" },
  --     {
  --       "<leader>/",
  --       function()
  --         require("telescope.builtin").current_buffer_fuzzy_find(require("telescope.themes").get_ivy({
  --           promp_position = "top",
  --           sorting_strategy = "ascending",
  --         }))
  --       end,
  --       desc = "Search in current buffer",
  --       silent = true,
  --       mode = "n",
  --       noremap = true,
  --     },
  --   },
  -- },
}
