# This section documents the root level of the configuration file.
live_config_reload = true
import = ["~/.config/alacritty/alacritty-theme/themes/one_dark.toml"]
ipc_socket = true


[env]
  TERM = "alacritty"

[window]
opacity=0.965
dynamic_padding = false
startup_mode = "Maximized"
dynamic_title = true
blur = true
decorations = "Buttonless" # Full / Buttonless
title = "terminal"

[window.dimensions]
columns = 160
lines = 80

[window.padding]
  x = 0
  y = 0

[scrolling]
  # Maximum number of lines in the scrollback buffer
  history = 65536
  # Number of line scrolled for every input scroll increment
  multiplier = 3


[mouse]
  hide_when_typing = true


[colors]
# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors = false
# when true, background will be transparent for hints, selections and search matches
transparent_background_colors = true 
  [colors.cursor]
    text = "#1E1E2E"
    cursor = "#B4BEFE"
  [colors.vi_mode_cursor]
    text = "#1E1E2E"
    cursor = "#B4BEFE"

[cursor]
style = "Block"

[font]
size = 15

[font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

# The bold font face
[font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

# The italic font face
[font.italic]
  family = "JetBrainsMono Nerd Font"

# Offset is the extra space around each character. offset.y can be thought of
# as modifying the linespacing, and offset.x as modifying the letter spacing.
[font.offset]
  x = 0
  y = 0

# Glyph offset determines the locations of the glyphs within their cells with
# the default being at the bottom. Increase the x offset to move the glyph to
# the right, increase the y offset to move the glyph upward.
[font.glyph_offset]
  x = 0
  y = 0


[debug]
render_timer = false
log_level = "Warn"

[selection]
# when true, selected text will be copied to the primary clipboard
save_to_clipboard = true

# [keyboard]
# bindings = [
#   { key = "Return", mods = ["Control"],chars = "\x1b[13;5u" },
#   { key = "Return", mods = ["Shift"],chars = "\x1b[13;2u" }
# ]



